### ISSUE TITLE
rails/docrails は４０４になっていあす

### ISSUE THREAD

**Issue by JongleurX** [yasslab/railsguides.jp#218]
継続的翻訳プロセスについて興味を持っており、改善につながるアイデアはいくつかあります。プロセスをやってみたいと思ってこちらのフォークをクローンしてみましたが、`rails/docrails` はアクセスしようとしたら４０４エラーを返しています。Railsチュートリアルのソースファイルは公開しなくなったのでしょうか？

**Comment by JongleurX** [comment]
rails/docrails から rails/rails のになったことが分かりました。したがって　https://github.com/yasslab/railsguides.jp/wiki/Translating-Rails-Guides を更新させていただきました。

**Comment by hanachin** [comment]
Wikiの更新ありがとうございます。

> rails/docrails から rails/rails のになったことが分かりました。

rails/docrailsはprivate repositoryになったみたいですね :eyes: 

https://twitter.com/rails/status/662035811265835008
https://github.com/rails/rails/commit/6cb1b6724c313c608cf4063fc22886faa19df9be

**Comment by yasulab** [comment]
Hi, thanks for your comment in Japanese ;)

> 継続的翻訳プロセスについて興味を持っており、改善につながるアイデアはいくつかあります。

We're changing RailsGuides' translation process into more effective and continuous way. We'll reveal the details at [RubyWorld Conference 2015](http://2015.rubyworld-conf.org/en/). So, it's not published yet. For now, we already have slides presented at GENGO Inc to explain how it works. Hope it helpful. cf. [
How We Continuously Translate RailsGuides (short version)](https://speakerdeck.com/yasulab/how-we-continuously-translate-railsguides-short-version)

> Railsチュートリアルのソースファイルは公開しなくなったのでしょうか？

Rails Tutorial by Michael Hartl (2e) was published under CC BY-SA 3.0, but it was changed into private repository from 3, which is shared only permitted translators. So, in order to follow his strategy, we also make our Japanese repository private.
