### ISSUE TITLE
5.0の最新版のドキュメントを取り込みたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#245]
cf.  [4-2-stableの最新版のドキュメントを取り込んだ #244](https://github.com/yasslab/railsguides.jp/pull/244#issuecomment-212225088)

**Comment by 1ulce** [comment]
getting startedの
5.3 記事を作成する内に、rails 5.0からの仕様で少し変わっている部分があります。
原文では
If you re-submit the form now, you may not see any change on the page. Don't worry! This is because Rails by default returns 204 No Content response for an action if we don't specify what the response should be. We just added the create action but didn't specify anything about how the response should be. In this case, the create action should save our new article to the database.
ですが、

これが5.0以前の翻訳(下記を)そのまま使っているので、エラー表示されないエラーかと勘違いしてしまうかと思われます。
「修正後フォームを再送信すると、今度はまたしても「a template is missing」エラーが表示されます。ひとまずこのエラーは無視しましょう。createアクションの役割は、記事をデータベースに保存することです。」

**Comment by yasulab** [comment]
報告ありがとうございます! こちら #266 でまとめていますので、そちらに追記しておきますね ;)

https://github.com/yasslab/railsguides.jp/issues/266#issuecomment-267287898

**Comment by hachi8833** [comment]
このissueもcloseしてよいと思います。@Yuppymam ご確認お願いします🙇
