### ISSUE TITLE
New content from association_basics.md

### ISSUE THREAD

**Issue by JuanitoFatas** [yasslab/railsguides.jp#70]
https://github.com/rails/rails/commit/017de712ee55c56f3d9ef9747d276dd0aa43244c#diff-6cb426645499101965568d643d991110R2247

:question: Question: How do you guys keep up with upstream? :smile:

**Comment by yasulab** [comment]
We follow the following steps for now:

1. (Manual) Use our master branch to keep up with upstream in a certain period (such as Rails 4.2 release)
2. (Manual) Upload the source files to [GTT](http://en.wikipedia.org/wiki/Google_Translator_Toolkit) to make use of [Translation Memory](http://en.wikipedia.org/wiki/Translation_memory)
3. (Manual) Translate the guides on GTT
4. (Automated) Download archived zip from GTT (cf. [download_archive.coffee](https://github.com/yasslab/railsguides.jp/blob/japanese/guides/download_archive.coffee)). 
5. (Automated) Unarchive, allocate, generate HTML files.
6. (Manual) Deploy it to Heroku.

Because there are some manual steps, it costs to iterate. So, we can't update so often for now :cold_sweat: 

For the future, I'd like to automate it as much as possible. So, I'm thinking of how to make it more efficient; for example, my ideas include:

1. Get GTT API (rejected once requested :sob: )
2. Quit from GTT and use (or implement) software that can handle translation memory to automate more.
3. Use [Gengo](http://gengo.com/) for updated sentences (if we can get money somehow)

I'm glad if you have good ideas or tools used for translation :pray:

**Comment by riseshia** [comment]
@yasulab 
これ、今更ですが、おわっているように見えます。　[Ref](https://github.com/yasslab/railsguides.jp/blame/master/guides/source/ja/association_basics.md#L2343-L2395)
閉じてもよいのではないでしょうか。

**Comment by yasulab** [comment]
Good call! Yes, I've update the guide very recently, so I've closed this issue ;) Thanks! 😸
